ProjectPineapple/Ananas2

server/db/models/index.js
server/db/models/product.js
server/db/models/user.js

Product model

---

server/db/models/index.js
server/db/models/user.js

User model

---

server/db/models/index.js
server/db/models/order.js
server/db/models/user.js

Order model

---

server/db/models/review.js

complete review model

---

server/db/models/order.js
server/db/models/product.js
server/db/models/user.js

Validations for all models -- note the currentPrice for Orders will be done in API route

add validations

---

script/seed.js

added Review fake seed data

---

script/seed.js

---
added associations for dummy data

added associations

---

script/seed.js
server/db/db.js
server/db/index.js
server/db/models/order.js
server/db/models/product.js
server/db/models/review.js
server/db/models/user.js
server/db/models/user.spec.js

Order hooks

---

script/seed.js
server/db/models/product.js

More seed work

---

server/db/models/index.js
server/db/models/product.js
server/db/models/user.js

- Comment in index.js about explicitly defining ProductOrder in order to include "price at purchase" column
- Reminder comment in product.js for how to map to and from newly-changed price in cents at the front end
- Comment in user.js suggesting indexes

Frances code review notes

---

client/components/checkoutForm.js
package-lock.json
package.json

---
Installed semantic and lodash, and created a barebones form.

Checkout form and barebones redux

---

server/api/products.js

Merging api routes for allProducts + singleProduct

Single product api routes

---

server/api/index.js
server/api/products.js

Tested GET allProducts, POST allProducts, GET/PUT/DELETE products/:productId
NOTE: On the front-end form for adding product photos, need to concatenate individual photo URLs into a photos array

all api products routes working on back end

---

client/store/allProducts.js
client/store/singleProduct.js

Updated to export default allProducts and singleProduct reducers in the redux store

updated default reducer name for products reducers

---

client/components/allProducts.js

Added Semantic UI product items for allProducts React component

Added Semantic UI product items for allProducts React component

---

client/components/ProductListing.js
client/components/allProducts.js
client/components/index.js
client/components/main.js

Added front end Route paths in Main.js for /products and /products/:productId paths

Main react routes

---

script/otherSeed.js
script/seed.js
server/api/orders.js
server/db/models/OrderLineItem.js
server/db/models/ProductOrder.js
server/db/models/index.js
server/db/models/order.js

---
Added Order methods to add line items effectively, cleaned up seed files. Renamed join table to OrderLineItems Table

Order in the cart - added several order methods and cleaned up the seed files. npm run smallseed should work 100%

---

client/components/allProducts.js
client/store/allProducts.js

Added createProduct thunk (confirmed it works on frontend) + put allProducts in grid view

AddProduct thunk

---

client/components/user-home.js
client/routes.js

Made a very rough skeleton of the logged-in user's home view; most e-commerce sites have fairly complicated views; might want to regroup about what we want to include / ignore.

v. rough skeleton of userHomeReact component

---

client/components/ProductListing.js
client/store/singleProduct.js

changes to singleProduct reducer

changes to single project reducer and ProductListing Component

---

client/components/allProducts.js
client/components/view-cart.js
server/db/models/product.js

when item is out of stock, it says so in your cart

"out of stock" and nice price

---

client/components/user-home.js

UserHome page; ternary for isAdmin + shows cart has items

---

client/components/view-cart.js

populates quantity

---

client/components/user-home-view.js
client/components/user-home.js

fixed ternary logic in userHomeView

---

client/components/AddProductForm.js
client/components/ProductListing.js
client/components/UpdateProductForm.js
client/routes.js
client/store/singleProduct.js

added routes for AddProduct, UpdateProduct, CheckoutForm

added routes for forms

---

client/components/view-cart.js
client/store/index.js
client/store/lineItem.js

- subtotal on bottom of cart screen
- WIP thunks for incrementing and decrementing line items in redux store

subtotal and begins to update line items

---

client/components/AddProductForm.js
client/components/ProductListing.js
client/components/UpdateProductForm.js
client/routes.js
server/api/products.js

added changes suggested by Collin

Key single product rerendering

---

client/store/allOrders.js

allOrders reducer

---

client/components/user-home.js

deleted reference to userHomeView

---

server/api/orders.js

commented out /:orderId api route so cart + products show

---

client/components/ViewCart.js

Checking out

---

client/components/ViewCart.js
client/components/allProducts.js
client/store/viewCart.js
server/api/orders.js
server/db/models/order.js

Updated POST route for /api/orders/:orderId; updated AddToCartThunk; updated allProducts component
WIP on ViewCart, which needs to refresh state

AddToCart works on product pages; needs refresh to update cart

---

client/routes.js

Made routes work on the front end to allow only admins into admin places, and even a 404 for routes not found

---

client/components/AddProductForm.js
client/components/ProductListing.js
client/components/UpdateProductForm.js
client/routes.js
client/store/addProduct.js
client/store/index.js
server/api/products.js

Added Update Product and Add Product Form -- don't merge the Routes file.

Add product form

---

client/components/user-home.js

Minor fix; added cart size to tab in userHome

added Cart qty to tab in userHome

---

client/components/AllOrders.js
client/components/ProductListing.js
client/components/UserOrders.js
client/components/ViewCart.js
client/components/auth-form.js
client/components/user-home.js
client/store/allOrders.js
client/store/index.js
client/store/userOrders.js
server/api/orders.js

---
added order views to homepage, for users and admins

Login steps

---

client/components/AllOrders.js
client/components/ProductListing.js
server/db/models/order.js

Changes to order model (times, statuses), changes to prices

changes to order times, prices

---

client/components/ViewCart.js
client/components/checkoutForm.js

refactored and cleaned up some logic -- subtotal now reflects quantity/stock discrepancies

View cart cleanup and subtotal

---

client/components/AllOrders.js
client/components/OrderList.js
client/components/SingleOrderView.js
client/components/UserOrders.js
client/store/userOrders.js
public/style.css
server/api/orders.js

order views in personal and admin pages updated with more detail

---

client/components/AllOrders.js
client/components/ProductListing.js
client/components/ViewCart.js
client/components/allProducts.js
client/store/viewCart.js
client/utilityMethods.js
server/api/orders.js

add utility methods for displaying price function

---

client/components/AddProductForm.js
client/components/allProducts.js
client/store/addProduct.js
client/store/allProducts.js

Things work, but tags no longer are drop down, just input

product form works hallelujah

---

client/components/allProducts.js
client/store/viewCart.js

get order id from viewCart's id instead of from OrderLineItems

---

client/components/AllOrders.js
client/components/ProductListing.js
client/components/ViewCart.js
client/components/allProducts.js
client/utilityMethods.js

adds utility method to get the available quantity of a product on an order with respect to the available stock

add getActualQuantity method

---

client/components/checkoutForm.js
server/api/stripe.js

stripe works

---

client/components/ViewCart.js
client/store/lineItem.js
server/api/cart.js

wip routes to update quantity of line item

---

client/components/ViewCart.js
client/components/allProducts.js
client/components/navbar.js
client/store/viewCart.js
package-lock.json
package.json
script/otherSeed.js
script/seed.js
server/api/orders.js
server/db/models/order.js

Just cart things - review together

---

script/seed.js
server/db/models/order.js

Just cart things -fixed big seed

---

client/components/ProductListing.js

Singlepageaddtocart - Add to cart button added and some styling added

---

client/components/AddToCartButton.js
client/components/ProductListing.js
client/components/allProducts.js

also has a message for out of stock and for few remaining

'Add to Cart' button disabled on empty stock

---

client/components/AddProductForm.js
client/components/UpdateProductForm.js
client/store/addProduct.js
client/store/updateProduct.js
server/api/products.js

Add and Update product form works + redirects

---

client/components/allProducts.js

some cleanup

---

client/components/AddToCartButton.js
client/components/ProductListing.js

disables when quantity in cart reaches remaining available stock

Add to cart button

---

client/components/allProducts.js

forgot this file in the last PR, whoops!

passes matched line item or {} in to Add to Cart button

---

client/components/AddReview.js
client/store/reviews.js

Minor syntax error to delete dimmer warning (addReview modal)

---

client/components/allProducts.js
client/routes.js
client/store/allProducts.js
package-lock.json
package.json
server/api/products.js

Pagination

---

client/components/AllOrders.js
client/components/UserOrders.js
client/utilityMethods.js

Listing orders

---

client/utilityMethods.js

improves utility method to return price (in dollars) instead of just comma separated

cents --> price

---

client/components/AddReview.js
client/store/addReview.js
client/store/index.js
client/store/reviews.js
server/api/reviews.js

addReview form works for stars + description & gives user error message if they don't submit a written description.
Next step: photos! Wahoo :)

addReview form working (minus photos)

---

client/components/AddReview.js
client/components/ProductReviews.js
server/api/reviews.js
server/db/models/review.js

Note: Still need to _format_ photos, but lower priority

user can add review photos (shows up on review)

---

client/components/ProductListing.js
client/components/allProducts.js
client/store/allProducts.js
client/store/index.js
client/store/totalItems.js
server/api/products.js

Pagination -as much as we want to do right now

---

client/components/checkoutForm.js
package-lock.json
package.json
server/api/cart.js
server/api/index.js
server/api/stripe.js

Checkout for the first time for the last time

---

client/components/OrderList.js
client/components/OrderModal.js
client/components/UserOrders.js
public/style.css

displays order info in modal on click

---

server/api/products.js
server/api/users.js
server/auth/index.js

Set variables for all current api routes with req.body; security in api routes still a WIP + will need to triple-check before deployment (I started a checklist)

set variables for req.body in api routes

---

client/components/reviews/AllReviews.js
client/components/reviews/ReviewList.js
client/components/user-home.js

NOTE: Still need to pull product name + image into the review; possible add: search bar or filter button

admins can now see all reviews on their dashboard

---

client/components/checkoutForm.js
client/store/checkout.js
server/api/cart.js

Order status updated to "paid" on backend if the payment is successful

Checkout order status

---

client/components/products/allProducts.js
server/api/products.js

can sort by id, price and stock of products

product sorting works

---

server/api/products.js

set default values for sortby and order to id and asc

quick fix to product view

---

server/api/cart.js
server/api/orders.js
server/api/reviews.js
server/api/users.js
server/db/models/user.js

Added isLoggedIn for the users; didn't work on isAdmin or isUser for EditForm since not functional + low priority;
Added isAdminOrOrderOriginator for orders api route

Security gateway for orders + users

---

client/components/auth-form.js
client/components/navbar.js
server/api/orders.js
server/auth/index.js

- Logout button disappears if you're logged out
- Updated login/signup display component
- Signup now working again (needed curly brackets in User.create function in api route)

Login/Logout/Sign-Up Display

---

client/components/EditUserForm.js
client/components/users/SingleUser.js
client/routes.js
client/store/addUser.js
client/store/index.js
server/api/users.js

????????????? but a fix, also doesn't log you out anymore when you edit someone :)

you can make admins users but not users admins

---

client/components/EditOrderForm.js
client/store/singleOrder.js
server/api/orders.js

YOU CAN EDIT ORDERS

---

client/components/navbar.js
client/store/user.js
server/api/orders.js
server/auth/index.js
server/db/models/session.js

Merge cart revisited

---

package.json

pinned Node to v12
